# Generated by Django 4.1.5 on 2023-01-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('RecipeId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Ingredients', models.CharField(max_length=500)),
                ('Instructions', models.CharField(max_length=500)),
                ('serving_size', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=500)),
                ('dateAdded', models.DateField()),
                ('dateModified', models.DateField()),
            ],
            options={
                'managed': True
            }
        ),
    ]
